-- [[ Setting options ]]
-- See `:help vim.o`
local opt = vim.opt

vim.o.hlsearch = true  -- Set highlight on search
vim.wo.number = true  -- Make line numbers default
opt.numberwidth = 2 -- TODO check what this does
opt.relativenumber = true  -- Make relative line numbers default
vim.o.mouse = 'a'  -- Enable mouse mode
vim.o.breakindent = true  -- Enable break indent 
vim.o.undofile = true  -- Save undo history 
vim.opt.undolevels = 10000
vim.o.ignorecase = true -- Case insensitive searching UNLESS /C or capital in search
opt.smartcase = true -- Don't ignore case with capitals
vim.o.updatetime = 250 -- Decrease update time
vim.o.timeoutlen = 300 -- Decrease update time
vim.wo.signcolumn = 'yes' -- keep signcolumn on by default
vim.o.termguicolors = true -- truecolor support
vim.o.completeopt = 'menu,menuone,noselect' -- Set completeopt to have a better completion experience 
-- opt.wildmode = "longest:full,full" -- Command-line completion mode
opt.swapfile = false -- disable swap file 
opt.clipboard = 'unnamedplus'  -- clipboard (install xclip on Linux)
-- opt.expandtab = true -- Use spaces instead of tabs
opt.cursorline = true -- Enable highlighting of the current line
-- opt.shiftwidth = 2 -- Size of an indent
-- opt.tabstop = 2 -- Number of spaces tabs count for
-- opt.smartindent = true -- Insert indents automatically
-- opt.scrolloff = 2 -- minimal number of screen lines to keep above and below the cursor.
-- opt.sidescrolloff = 2 -- minimal number of screen lines to keep left and right of the cursor.
-- opt.splitbelow = true -- Put new windows below current
-- opt.splitright = true -- Put new windows right of current
-- opt.spelllang = { "en" }
-- opt.wrap = true -- Disable line wrap
-- opt.autowrite = true -- Enable auto write
-- opt.conceallevel = 3 -- Hide * markup for bold and italic
-- opt.confirm = true -- Confirm to save changes before exiting modified buffer
-- opt.formatoptions = "jcroqlnt" -- tcqj
-- opt.grepformat = "%f:%l:%c:%m"
-- opt.grepprg = "rg --vimgrep"
-- opt.inccommand = "nosplit" -- preview incremental substitute
-- opt.laststatus = 3 -- global statusline
-- opt.list = true -- Show some invisible characters (tabs...
-- opt.pumblend = 10 -- Popup blend
-- opt.pumheight = 10 -- Maximum number of entries in a popup
-- opt.sessionoptions = { "buffers", "curdir", "tabpages", "winsize" }
-- opt.shiftround = true -- Round indent
-- opt.shortmess:append { W = true, I = true, c = true }
-- opt.showmode = false -- Dont show mode since we have a statusline
-- opt.winminwidth = 5 -- Minimum window width
-- opt.ruler = false
